let
    Source = MongoDBAtlasODBC.Contents("mongodb://localhost", "db2", []),
    reports_Database = Source{[Name="reports",Kind="Database"]}[Data],
    transforms_Table = reports_Database{[Name="transforms",Kind="Table"]}[Data],
    #"Lowercased Text" = Table.TransformColumns(transforms_Table,{
        {"str0", Text.Lower, type text},
        {"str1", Text.Upper, type text},
        {"str2", Text.Length, type text},
        {"num0", each Number.Round(_, 5), type number},
        {"num1", Number.RoundUp, type number},
        {"num2", Number.Abs, type number},
        {"num3", Number.Log10, type number},
        {"num4", each Number.Power(_, 15), type number},
        {"num5", each Number.Power(_, 2), type number},
        {"num6", each Number.Power(_, 3), type number},
        {"num7", Number.Sqrt, type number},
        {"date0", Date.Year, type date},
        {"date1", Date.StartOfYear, type date},
        {"date2", Date.EndOfYear, type date},
        {"date4", Date.StartOfQuarter, type date},
        {"date5", Date.EndOfQuarter, type date},
        {"date6", Date.Month, type date},
        {"date7", Date.StartOfMonth, type date},
        {"date8", Date.EndOfMonth, type date},
        {"date9", Date.WeekOfYear, type date},
        {"date10", Date.StartOfWeek, type date},
        {"date11", Date.EndOfWeek, type date},
        {"date12", Date.Day, type date},
        {"date13", Date.DayOfWeek, type date},
        {"date14", Date.StartOfDay, type date},
        {"date15", Date.EndOfDay, type date},
        {"date16", Date.EndOfDay, type date},
        {"date17", Time.Hour, type date},
        {"date18", Time.StartOfHour, type date},
        {"date19", Time.EndOfHour, type date},
        {"date20", Time.Minute, type date},
        {"date21", Time.Second, type date}
    }),
    #"Replaced Value" = Table.ReplaceValue(#"Lowercased Text","4","hello",Replacer.ReplaceText,{"str3"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value", 1.7E-27, 42.5, Replacer.ReplaceValue, {"num8"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",#datetime(2013, 9, 15, 0, 0, 0),#datetime(2012, 8, 12, 23, 0, 0),Replacer.ReplaceValue,{"date22"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", true, false, Replacer.ReplaceValue,{"bool0"})
in
    #"Replaced Value3"
